development: &default
  adapter: postgresql
  encoding: unicode
  database: cookry_development
  pool: 5
  username: postgres
  password: cookry

test: &TEST
  <<: *default
  database: cookry_test

production:
  <<: *default
  database: cookry

cucumber:
  <<: *TEST