# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c34d82755ae9d845d99f8b26431646022fcd29fa5c5c0f9e895d0bbcb35bc582b0b740fb42493555efc22d1a28edb544f932426adcf489799d6b92cf9d952961

test:
  secret_key_base: 904a81277f12b25bacc1ac10124cc0f7bf221ef1f2fa6e66119f7ecf9123ee86b9eacb2528fe8937125c1eae1545f289d809fd82d45af46ee40784d8595eb18c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
